### ISSUE TITLE
With and lookup subexpression

### ISSUE THREAD

**Issue by tmpfs** [sunng87/handlebars-rust#353] opened 2020-07-09 07:15 UTC
Thanks for this handlebars implementation I have been enjoying using it very much. I think I *might* have hit a bug...

Not sure if this is related to #343 but it appears that there is a bug using lookup in a sub-expression in conjunction with a with block helper.

This code does not work:

```handlebars
{{#with (lookup context.config.authors "tmpfs")}}
{{json this}}
{{/with}}
```

Note that `json` is just a helper that serializes and prints as JSON for  debugging. In this case the context is not changed and `this` refers incorrectly to the outer context.

But I know the object exists because if I change it to:

```handlebars
{{#with context.config.authors.tmpfs)}}
{{json this}}
{{/with}}
```

Then the context is correct.

I am trying to do dynamic lookup of a key in an object so this is all actually going to be a partial called like this `{{>author id="tmpfs"}}` but at the moment it looks like I can't achieve what I want.

I took a look at the code and I thought at first it was an issue with the `lookup` helper but adding a test case to the code made me think it may be an issue with the `with` helper instead.

I will put together something simple to try to reproduce it shortly then maybe you can advise where the issue might be. Thanks!

**Comment by tmpfs** [comment] 2020-07-09 07:23
So here is minimum viable program:

```rust
#[macro_use]
extern crate serde_json;

use handlebars::Handlebars;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let data = json!({"a": {"b": {"c": "d"}}});
    let hb = Handlebars::new();
    let template = "{{#with (lookup a.b \"c\")}}{{this}}{{/with}}";
    println!("{}", hb.render_template(template, &data)?);
    Ok(())
}
```

Prints `[object]`, I expected it to print `d`.

**Comment by sunng87** [comment] 2020-07-12 02:41
This might be related to #343 that `with` and `each` doesn't handle derived value well.

**Comment by chaserhkj** [comment] 2020-07-20 02:29
I took a bit more time looking into this one, it's very similar to #343, but it's actually not the same issue.

In #343 the primary issue is with block parameters. In `BlockParams`  we could bind a param by binding a name to a path into the data model (`add_path`) or bind a param by binding a name to an actual JSON value (`add_value`). And #343 showed that when trying to bind a derived value to block parameters, `with` handled it right by using `add_value` when the bound target does not have a path, but `each` handled it wrong. This could be easily fixed by using `add_value` correctly in `each` and should already be fixed in PR #364 

But for this issue, the problem is actually a bit deeper. Using relative paths instead of using block parameters to refer to values in a block helper requires the lookup of block base values to be performed correctly. As far as I understand the current code, this lookup inside a block helper is done by performing lookup relative to a "block base path". This actually **assumes that the values being looked up inside a block helper is always part of the main data model**, and making it completely impossible to support lookup into derived values inside block helpers.

In the code there's actually a `base_value` field for block contexts which could be a very good place to store derived values to be looked up against, but it's not in use currently ([here](https://github.com/sunng87/handlebars-rust/blob/e36f81bdd7776c59e59ec25d6e6677bbd7a70d0d/src/block.rs#L61)) 

I'd suggest changing the lookup mechanism in blocks and reviving this `base_value` field to specifically handle derived values when `base_path` is not definable. Or probably we should merge base_value and base_path into some enum representing a source of lookup.

**Comment by sunng87** [comment] 2020-07-20 09:40
Thank you @chaserhkj ! In #355 I have been working on `base_value` support for derived value.

**Closed** 2020-07-23 01:26 UTC
Labels: bug

**Comment by tmpfs** [comment] 2020-07-23 01:44
Thank you @suung87 - I look forward to getting this patch in the next release, much appreciated :+1:
