### ISSUE TITLE
Hash parameters in partials don't seem to work

### ISSUE THREAD

**Issue by tiffany352** [sunng87/handlebars-rust#107] opened 2016-10-08 19:22 UTC
``` handlebars
{{> foo abc=true}}
```

``` handlebars
{{! foo.hbs }}
{{#if abc}}
works
{{/if}}
```

Doesn't work for me (using handlebars-iron, in case that's important). It looks like this is supposed to work, and it looks like the examples for the JS version use it. I might be wrong about how these are supposed to work - the documentation on handlebars in general is kind of unhelpful.

**Comment by sunng87** [comment] 2016-10-09 14:34
The handlebars 4.0 partial should work with `partial4` feature turned on. I just added a test case for this scenario: 6602aef

The issue is handlebars-iron doesn't have feature option to turn it on.

**Comment by sunng87** [comment] 2016-10-17 13:58
Please use the latest handlebars-iron with features `partial4` turned on.

**Comment by sunng87** [comment] 2016-12-12 13:29
Will close this since `partial4` becomes default in 0.23

**Closed by sunng87** 2016-12-12 13:29 UTC
Labels: question
