### ISSUE TITLE
Disappearing whitespace after an expression?

### ISSUE THREAD

**Issue by ppentchev** [sunng87/handlebars-rust#467] opened 2021-09-07 10:50 UTC
Hi,

Thanks a lot for writing and maintaining handlebars-rust!

To be honest, I am not even sure if this is really an issue or if this is how Handlebars is supposed to work. I am not using it for rendering HTML, so whitespace could be significant, although in this particular case I have a usable workaround.

In short, could you take a look at https://gitlab.com/ppentchev/test-whitebars and specifically https://gitlab.com/ppentchev/test-whitebars/-/blob/main/src/bin/whitebars.rs - it seems that the "unquoted" template, the one that does not have apostrophes around the `{{this.name}}` part - will eliminate the space character after this particular expression, before the `=>` token. Is this expected? Have I - and it is very, very, very much possible that I have - misunderstood the Handlebars documentation WRT whitespace handling? If so, of course, feel free to close this issue or let me know and I will close it myself, and apologies for wasting your time! :)

Thanks in advance for your time, and keep up the great work!

**Comment by sunng87** [comment] 2021-09-08 14:33
I managed to reproduce this issue with your case. It seems to be a bug with our template parser. The whitespaces behind `}}` was ignored.

**Comment by sunng87** [comment] 2021-09-09 15:19
Fixed in #468

**Closed by sunng87** 2021-09-09 15:19 UTC
